---
- name: Add SSH public key
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Append SSH public key
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ssh_key}}"
