---
- name: Add SSH public key
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Append SSH public key
      ansible.builtin.shell: echo "{{ssh_key}}" > /home/ubuntu/.ssh/authorized_keys

    - name: Cat authorized_keys file
      ansible.builtin.shell: cat /home/ubuntu/.ssh/authorized_keys
      register: ssh_keys

    - name: Display SSH keys
      ansible.builtin.debug:
        var: ssh_keys.stdout
