---
- name: Reboot MGC VM instance
  hosts: all
  gather_facts: no

  tasks:
    - name: Reboot virtual machine
      command: >
        mgc virtual-machine instances reboot "{{ lookup('env','VM_INSTANCE_ID') }}"
