---
- name: Reboot MGC VM instance
  hosts: all
  gather_facts: yes

  tasks:
  - name: Reboot virtual machine "{{nome}}"
    command: mgc virtual-machine instances reboot "{{VM_INSTANCE_ID}}"
    register: reboot_result

  - name: Resultado "{{nome}}"
    debug:
      var: reboot_result
      
