---
- name: Reboot MGC VM instance
  hosts: all
  gather_facts: yes

  tasks:
  - name: Reboot virtual machine Senac
    command: mgc virtual-machine instances reboot "{{VM_INSTANCE_ID_senac}}"
    register: reboot_result

  - name: Show command output
    debug:
      var: reboot_result
      
  - name: Reboot virtual machine Gtfoods
    command: mgc virtual-machine instances reboot "{{VM_INSTANCE_ID_gtfoods}}"
    register: reboot_result

  - name: Show command output
    debug:
      var: reboot_result
